name: Ubuntu 18.04

on: [push]

jobs:
  buildubuntu:
    name: build_ubuntu_18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt -y install tclsh pkg-config libssl-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: libsrtnet_linux
        path: ./libsrtnet.a
    - uses: actions/upload-artifact@v2
      with:
        name: libsrt_linux
        path: ./srt/libsrt.a
      




