name: C/C++ CI

on: [push]

jobs:
  buildubuntu:
    name: build_ubuntu_18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
      
  buildmac:
    name: build_macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make

      
  buildwin:
    name: build_windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake --config Release .
    - name: build
      run: cmake --build .




