name: unit_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-release:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: CMake set-up for release
        run: |
          sudo apt update && sudo apt install -y libgtest-dev
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      - name: Build release
        run: |
          cd build
          make runUnitTests
      - name: Run tests with release
        run: |
          cd build
          ./runUnitTests

  test-debug:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: CMake set-up for debug
        run: |
          sudo apt update && sudo apt install -y libgtest-dev
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build debug
        run: |
          cd build
          make runUnitTests
      - name: Run tests with debug
        run: |
          cd build
          ./runUnitTests
