name: Windows

on: [push]

jobs:
  buildwin:
    name: build_windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: install OpenSSL
      run: choco install openssl > null
    - name: cmake
      run: cmake --config Release .
    - name: build
      run: cmake --build . --config Release
      

