name: Windows x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get OpenSSL
      run: choco install openssl
    - name: CMake set-up
      run: cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: cmake --build . --config Release
    - uses: actions/upload-artifact@v2
      with:
        name: libsrtnet_win_x64
        path: ./Release/srtnet.lib
    - uses: actions/upload-artifact@v2
      with:
        name: libsrt_win_x64
        path: ./srt/Release/srt_static.lib
